image: docker:dind

services:
 - docker:dind

variables: 
  DOCKER_TLS_CERTDIR: ""
  GIT_SUBMODULE_STRATEGY: recursive

build_hijack:
  stage: build

  script:
    - unset DOCKER_HOST
    - docker login $CI_REGISTRY -u $REGISTRY_USER -p $REGISTRY_PASSWORD
    - docker build -t hijack:latest . 
    - docker run hijack:latest hj list
    - docker tag hijack:latest registry.gitlab.slovendor.com/hijack:latest
    - docker push registry.gitlab.slovendor.com/hijack:latest
